DELETE FROM doctor_illness;
DELETE FROM doctor;
DELETE FROM hospital;
DELETE FROM "user";
DELETE FROM illness_symptom;
DELETE FROM illness;
DELETE FROM symptom;

INSERT INTO symptom (name) VALUES
('Fever'),
('Cough'),
('Fatigue'),
('Shortness of breath'),
('Chest pain'),
('Cough with phlegm'),
('Sweating'),
('Frequent urination'),
('Painful urination'),
('Lower abdominal pain'),
('Diarrhea'),
('Vomiting'),
('Abdominal cramps'),
('Severe pain in the back or side'),
('Blood in urine'),
('Abdominal pain, often starting around the navel and shifting to the lower right abdomen'),
('Loss of appetite'),
('Nausea and vomiting'),
('Increased thirst'),
('Sensitivity to light or sound'),
('Wheezing'),
('Chronic cough'),
('Excessive mucus production'),
('Sudden numbness or weakness in the face, arm, or leg'),
('Confusion'),
('Trouble speaking or understanding speech'),
('Dizziness'),
('Blurred or double vision'),
('Excessive worry'),
('Restlessness'),
('Heartburn'),
('Regurgitation'),
('Joint pain and swelling'),
('Morning stiffness'),
('Joint pain'),
('Stiffness'),
('Limited range of motion'),
('Weight changes'),
('Changes in skin and hair texture'),
('Swelling in the legs and ankles'),
('Changes in urination'),
('Intense joint pain'),
('Redness'),
('Persistent sad, anxious, or "empty" mood'),
('Loss of interest or pleasure in activities'),
('Sleep disturbances'),
('Upper abdominal pain'),
('Tender abdomen'),
('Seizures'),
('Temporary confusion'),
('Staring spell'),
('Numbness or weakness'),
('Difficulty walking'),
('Persistent, unexplained fatigue'),
('Muscle aches'),
('Skin rashes'),
('Jaundice (yellowing of the skin and eyes)'),
('Abdominal pain, usually on the left side'),
('Bloating'),
('Changes in bowel habits'),
('Pelvic pain'),
('Painful periods'),
('Painful intercourse'),
('Rapid heart rate'),
('Changes in menstrual cycle'),
('Abdominal swelling'),
('Easy bruising and bleeding'),
('Stiff neck'),
('Tremors'),
('Slowness of movement'),
('Changes in energy and activity levels'),
('Impaired sleep'),
('Hallucinations'),
('Delusions'),
('Disorganized thinking'),
('Fractures with minimal trauma'),
('Loss of height over time'),
('Back pain'),
('Bulge in the abdomen or groin'),
('Burning or aching sensation'),
('Coughing up blood'),
('Cold intolerance'),
('Heat intolerance'),
('Rectal bleeding'),
('Itching or irritation'),
('Pain or discomfort'),
('Difficulty starting or stopping urination'),
('Weak urine stream'),
('Gradual loss of peripheral vision'),
('Blurred vision'),
('Eye pain or discomfort'),
('Weakness'),
('Pale skin'),
('Runny or stuffy nose'),
('Itchy or watery eyes'),
('Dark yellow urine'),
('Intense headache'),
('Nausea'),
('Dry mouth and skin');

INSERT INTO illness (name) VALUES
('Influenza (Flu)'),
('Pneumonia'),
('Heart Attack'),
('Urinary Tract Infection (UTI)'),
('Gastroenteritis'),
('Kidney Stones'),
('Appendicitis'),
('Diabetes'),
('Migraine'),
('Asthma'),
('Chronic Obstructive Pulmonary Disease (COPD)'),
('Stroke'),
('Hypertension (High Blood Pressure)'),
('Anxiety Disorders'),
('Gastroesophageal Reflux Disease (GERD)'),
('Peptic Ulcer Disease'),
('Rheumatoid Arthritis'),
('Osteoarthritis'),
('Thyroid Disorders'),
('Coronary Artery Disease (CAD)'),
('Chronic Kidney Disease (CKD)'),
('Gout'),
('Depression'),
('Pancreatitis'),
('Epilepsy'),
('Multiple Sclerosis (MS)'),
('Chronic Fatigue Syndrome'),
('Celiac Disease'),
('Lupus (Systemic Lupus Erythematosus)'),
('Hepatitis'),
('Diverticulitis'),
('Endometriosis'),
('Pulmonary Embolism'),
('Ovarian Cysts'),
('Cirrhosis'),
('Meningitis'),
('Parkinsons Disease'),
('Bipolar Disorder'),
('Schizophrenia'),
('Osteoporosis'),
('Hernia'),
('Tuberculosis'),
('Hypothyroidism'),
('Hyperthyroidism'),
('Hemorrhoids'),
('Prostate Problems'),
('Glaucoma'),
('Anemia'),
('Allergies'),
('Dehydration');

INSERT INTO illness_symptom  (illness_id, symptom_id) VALUES
((SELECT id from illness where name = 'Influenza (Flu)'), (SELECT id from symptom WHERE name = 'Fever')),
((SELECT id from illness where name = 'Influenza (Flu)'), (SELECT id from symptom WHERE name = 'Cough')),
((SELECT id from illness where name = 'Influenza (Flu)'), (SELECT id from symptom WHERE name = 'Fatigue')),

((SELECT id from illness where name = 'Pneumonia'), (SELECT id from symptom WHERE name = 'Shortness of breath')),
((SELECT id from illness where name = 'Pneumonia'), (SELECT id from symptom WHERE name = 'Chest pain')),
((SELECT id from illness where name = 'Pneumonia'), (SELECT id from symptom WHERE name = 'Cough with phlegm')),

((SELECT id from illness where name = 'Heart Attack'), (SELECT id from symptom WHERE name = 'Chest pain')),
((SELECT id from illness where name = 'Heart Attack'), (SELECT id from symptom WHERE name = 'Shortness of breath')),
((SELECT id from illness where name = 'Heart Attack'), (SELECT id from symptom WHERE name = 'Sweating')),

((SELECT id from illness where name = 'Urinary Tract Infection (UTI)'), (SELECT id from symptom WHERE name = 'Frequent urination')),
((SELECT id from illness where name = 'Urinary Tract Infection (UTI)'), (SELECT id from symptom WHERE name = 'Painful urination')),
((SELECT id from illness where name = 'Urinary Tract Infection (UTI)'), (SELECT id from symptom WHERE name = 'Lower abdominal pain')),

((SELECT id from illness where name = 'Gastroenteritis'), (SELECT id from symptom WHERE name = 'Diarrhea')),
((SELECT id from illness where name = 'Gastroenteritis'), (SELECT id from symptom WHERE name = 'Vomiting')),
((SELECT id from illness where name = 'Gastroenteritis'), (SELECT id from symptom WHERE name = 'Abdominal cramps')),

((SELECT id from illness where name = 'Kidney Stones'), (SELECT id from symptom WHERE name = 'Severe pain in the back or side')),
((SELECT id from illness where name = 'Kidney Stones'), (SELECT id from symptom WHERE name = 'Blood in urine')),
((SELECT id from illness where name = 'Kidney Stones'), (SELECT id from symptom WHERE name = 'Painful urination')),

((SELECT id from illness where name = 'Appendicitis'), (SELECT id from symptom WHERE name = 'Abdominal pain, often starting around the navel and shifting to the lower right abdomen')),
((SELECT id from illness where name = 'Appendicitis'), (SELECT id from symptom WHERE name = 'Loss of appetite')),
((SELECT id from illness where name = 'Appendicitis'), (SELECT id from symptom WHERE name = 'Nausea and vomiting')),

((SELECT id from illness where name = 'Diabetes'), (SELECT id from symptom WHERE name = 'Increased thirst')),
((SELECT id from illness where name = 'Diabetes'), (SELECT id from symptom WHERE name = 'Frequent urination')),
((SELECT id from illness where name = 'Diabetes'), (SELECT id from symptom WHERE name = 'Fatigue')),

((SELECT id from illness where name = 'Migraine'), (SELECT id from symptom WHERE name = 'Intense headache')),
((SELECT id from illness where name = 'Migraine'), (SELECT id from symptom WHERE name = 'Nausea')),
((SELECT id from illness where name = 'Migraine'), (SELECT id from symptom WHERE name = 'Sensitivity to light or sound')),

((SELECT id from illness where name = 'Asthma'), (SELECT id from symptom WHERE name = 'Shortness of breath')),
((SELECT id from illness where name = 'Asthma'), (SELECT id from symptom WHERE name = 'Wheezing')),
((SELECT id from illness where name = 'Asthma'), (SELECT id from symptom WHERE name = 'Cough')),

((SELECT id from illness where name = 'Chronic Obstructive Pulmonary Disease (COPD)'), (SELECT id from symptom WHERE name = 'Shortness of breath')),
((SELECT id from illness where name = 'Chronic Obstructive Pulmonary Disease (COPD)'), (SELECT id from symptom WHERE name = 'Chronic cough')),
((SELECT id from illness where name = 'Chronic Obstructive Pulmonary Disease (COPD)'), (SELECT id from symptom WHERE name = 'Excessive mucus production'));

INSERT INTO hospital (name, lat, long, hour_start, hour_end, profile_image, address) VALUES 
('Gangnam hospital', 37.517235, 127.047325, '08:00', '18:00', 'https://picsum.photos/200', 'Seoul, gangmam, lol'),
('Hongdae hospital', 37.5519, 126.9918, '08:00', '18:00', 'https://picsum.photos/200', 'Seoul, hongdae, yes'),
('Sindorim hospital', 37.5100, 126.8822, '09:30', '21:00', 'https://picsum.photos/200', 'Seoul, sindorim, yes'),
('Nowon hospital', 37.6525, 127.0750, '09:00', '20:00', 'https://picsum.photos/200', 'Seoul, nowon, yes'),
('Itaewon hospital', 37.5385, 126.9925, '08:00', '18:00', 'https://picsum.photos/200', 'Seoul, itaewon, yes'),
('Yongsan hospital', 37.5314, 126.9799, '08:00', '18:00', 'https://picsum.photos/200', 'Seoul, yongsan, yes'),
('Yeouido hospital', 37.5259, 126.9269, '08:00', '18:00', 'https://picsum.photos/200', 'Seoul, yeouido, yes');

INSERT INTO doctor (firstname, lastname, english, hospital_id) VALUES
('Michelle', 'Kim', true, (SELECT id from hospital where name = 'Gangnam hospital')),
('Elizabeth', 'Renderos', true, (SELECT id from hospital where name = 'Hongdae hospital')),
('Suzie', 'Choi', true, (SELECT id from hospital where name = 'Sindorim hospital')),
('Sarah', 'Kim', true, (SELECT id from hospital where name = 'Nowon hospital')),
('Michael', 'Scott', false, (SELECT id from hospital where name = 'Itaewon hospital')),
('Dwight', 'Schrute', false, (SELECT id from hospital where name = 'Yongsan hospital')),
('Jim', 'Halpert', true, (SELECT id from hospital where name = 'Yeouido hospital')),
('Pam', 'Beasley', true, (SELECT id from hospital where name = 'Gangnam hospital')),
('Creed', 'Barington', false, (SELECT id from hospital where name = 'Hongdae hospital')),
('Stanley', 'Hudson', true, (SELECT id from hospital where name = 'Sindorim hospital'));

INSERT INTO doctor_illness (doctor_id, illness_id) VALUES
((SELECT id from doctor where firstname = 'Michelle'), (SELECT id from illness WHERE name = 'Influenza (Flu)')),
((SELECT id from doctor where firstname = 'Michelle'), (SELECT id from illness WHERE name = 'Pneumonia')),
((SELECT id from doctor where firstname = 'Michelle'), (SELECT id from illness WHERE name = 'Heart Attack')),
((SELECT id from doctor where firstname = 'Michelle'), (SELECT id from illness WHERE name = 'Migraine')),
((SELECT id from doctor where firstname = 'Elizabeth'), (SELECT id from illness WHERE name = 'Influenza (Flu)')),
((SELECT id from doctor where firstname = 'Elizabeth'), (SELECT id from illness WHERE name = 'Urinary Tract Infection (UTI)')),
((SELECT id from doctor where firstname = 'Suzie'), (SELECT id from illness WHERE name = 'Influenza (Flu)')),
((SELECT id from doctor where firstname = 'Suzie'), (SELECT id from illness WHERE name = 'Gastroenteritis')),
((SELECT id from doctor where firstname = 'Suzie'), (SELECT id from illness WHERE name = 'Asthma')),
((SELECT id from doctor where firstname = 'Sarah'), (SELECT id from illness WHERE name = 'Pneumonia')),
((SELECT id from doctor where firstname = 'Sarah'), (SELECT id from illness WHERE name = 'Gastroenteritis')),
((SELECT id from doctor where firstname = 'Michael'), (SELECT id from illness WHERE name = 'Pneumonia')),
((SELECT id from doctor where firstname = 'Michael'), (SELECT id from illness WHERE name = 'Kidney Stones')),
((SELECT id from doctor where firstname = 'Michael'), (SELECT id from illness WHERE name = 'Diabetes')),
((SELECT id from doctor where firstname = 'Dwight'), (SELECT id from illness WHERE name = 'Pneumonia')),
((SELECT id from doctor where firstname = 'Dwight'), (SELECT id from illness WHERE name = 'Kidney Stones')),
((SELECT id from doctor where firstname = 'Dwight'), (SELECT id from illness WHERE name = 'Appendicitis')),
((SELECT id from doctor where firstname = 'Dwight'), (SELECT id from illness WHERE name = 'Diabetes')),
((SELECT id from doctor where firstname = 'Jim'), (SELECT id from illness WHERE name = 'Heart Attack')),
((SELECT id from doctor where firstname = 'Jim'), (SELECT id from illness WHERE name = 'Kidney Stones')),
((SELECT id from doctor where firstname = 'Pam'), (SELECT id from illness WHERE name = 'Heart Attack')),
((SELECT id from doctor where firstname = 'Pam'), (SELECT id from illness WHERE name = 'Appendicitis')),
((SELECT id from doctor where firstname = 'Creed'), (SELECT id from illness WHERE name = 'Influenza (Flu)')),
((SELECT id from doctor where firstname = 'Creed'), (SELECT id from illness WHERE name = 'Asthma')),
((SELECT id from doctor where firstname = 'Stanley'), (SELECT id from illness WHERE name = 'Appendicitis')),
((SELECT id from doctor where firstname = 'Stanley'), (SELECT id from illness WHERE name = 'Urinary Tract Infection (UTI)')),
((SELECT id from doctor where firstname = 'Stanley'), (SELECT id from illness WHERE name = 'Chronic Obstructive Pulmonary Disease (COPD)'));